//internal import

import Sidebar from "@components/user-dashboard/Sidebar";

export const metadata = {
  title: "KachaBazar - Next Clothing Store e-commerce Template",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <>
      <div className="mx-auto max-w-screen-2xl px-3 sm:px-10">
        <div className="py-10 lg:py-12 flex flex-col lg:flex-row w-full">
          <div className="flex-shrink-0 w-full lg:w-80 mr-7 lg:mr-10  xl:mr-10 ">
            <Sidebar />
          </div>

          <div className="w-full bg-white mt-4 lg:mt-0 p-4 sm:p-5 lg:p-8 rounded-md overflow-hidden">
            {children}
          </div>
        </div>
      </div>
    </>
  );
}
